
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.


/opt/slurm/var/spool/slurmd/job59936/slurm_script: line 23: cd: /home/est_posgrado_natalia.huitzil/GraficasResul/Metrica/debUOPP: No such file or directory
/home/est_posgrado_natalia.huitzil/.conda/envs/compu21/lib/python3.10/site-packages/skimage/metrics/simple_metrics.py:163: RuntimeWarning: divide by zero encountered in double_scalars
  return 10 * np.log10((data_range ** 2) / err)
Traceback (most recent call last):
  File "/home/est_posgrado_natalia.huitzil/ClusterAB/ClusterA/GraficasResul/MetricaOPP/debUOPP/MetricAngImgKodim_i_debUopp.py", line 624, in <module>
    pritnTab1(datAng,25)
  File "/home/est_posgrado_natalia.huitzil/ClusterAB/ClusterA/GraficasResul/MetricaOPP/debUOPP/MetricAngImgKodim_i_debUopp.py", line 622, in pritnTab1
    print('kodim' + str(i+1), ' & ' ,"{:.4f}".format(Data[i,1]) , ' & ', "{:.4f}".format(Data[i,2]) ,' & ', "{:.4f}".format(Data[i,3]),' & ', "{:.4f}".format(Data[i,4]) ,' & ', "{:.4f}".format(Data[i,5]),' & ', "{:.4f}".format(Data[i,6]),' \\\\' )
IndexError: index 2 is out of bounds for axis 0 with size 2
